# -*- coding: utf-8 -*-

# English and Kannada disease information used by app.py

disease_details = {'Apple___Apple_scab': {'en': {'cause': 'Apple scab is caused by the fungus Venturia inaequalis, which '
                                        'spreads rapidly during cool and wet weather.',
                               'symptoms': ['Olive-green or dark spots on leaves',
                                            'Dark scabby lesions on fruits',
                                            'Premature leaf drop',
                                            'Reduced fruit quality'],
                               'solution': ['Remove and destroy infected leaves and fallen fruits.',
                                            'Apply recommended fungicides such as Captan or Mancozeb.',
                                            'Prune trees to improve air circulation.',
                                            'Plant resistant apple varieties whenever possible.']},
                        'kn': {'cause': 'ಸೇಬಿನ ಸ್ಕ್ಯಾಬ್ ರೋಗವು Venturia inaequalis ಎಂಬ ಶಿಲೀಂಧ್ರದಿಂದ '
                                        'ಉಂಟಾಗುತ್ತದೆ. ಇದು ತಂಪು ಮತ್ತು ತೇವವಾದ ಹವಾಮಾನದಲ್ಲಿ ವೇಗವಾಗಿ ಹರಡುತ್ತದೆ.',
                               'symptoms': ['ಎಲೆಗಳ ಮೇಲೆ ಆಲಿವ್ ಹಸಿರು ಅಥವಾ ಗಾಢ ಕಲೆಗಳು',
                                            'ಹಣ್ಣುಗಳ ಮೇಲೆ ಕಪ್ಪು ಗಟ್ಟಿಯಾದ ಗಾಯದ ಕಲೆಗಳು',
                                            'ಎಲೆಗಳು ಬೇಗ ಉದುರುವುದು',
                                            'ಹಣ್ಣಿನ ಗುಣಮಟ್ಟ ಕಡಿಮೆಯಾಗುವುದು'],
                               'solution': ['ಸೋಂಕಿತ ಎಲೆಗಳು ಮತ್ತು ಬಿದ್ದ ಹಣ್ಣುಗಳನ್ನು ತೆಗೆದು ನಾಶಪಡಿಸಿ.',
                                            'ಕ್ಯಾಪ್ಟಾನ್ ಅಥವಾ ಮ್ಯಾಂಕೋಜೆಬ್\u200cನಂತಹ ಶಿಫಾರಸು ಮಾಡಿದ '
                                            'ಶಿಲೀಂಧ್ರನಾಶಕ ಬಳಸಿ.',
                                            'ಗಾಳಿಯ ಹರಿವು ಹೆಚ್ಚಿಸಲು ಮರದ ಕೊಂಬೆಗಳನ್ನು ಕತ್ತರಿಸಿ.',
                                            'ಸಾಧ್ಯವಾದರೆ ರೋಗನಿರೋಧಕ ಸೇಬಿನ ತಳಿಗಳನ್ನು ಬೆಳೆಸಿ.']}},
 'Apple___Black_rot': {'en': {'cause': 'Black rot is caused by the fungus Botryosphaeria obtusa.',
                              'symptoms': ['Purple spots on leaves',
                                           'Black rotten fruits',
                                           'Cankers on branches',
                                           'Leaf wilting'],
                              'solution': ['Prune infected branches immediately.',
                                           'Remove infected fruits from the orchard.',
                                           'Apply fungicides during the growing season.',
                                           'Maintain orchard sanitation.']},
                       'kn': {'cause': 'ಕಪ್ಪು ಕೊಳೆ ರೋಗವು Botryosphaeria obtusa ಎಂಬ ಶಿಲೀಂಧ್ರದಿಂದ ಉಂಟಾಗುತ್ತದೆ.',
                              'symptoms': ['ಎಲೆಗಳ ಮೇಲೆ ನೇರಳೆ ಬಣ್ಣದ ಕಲೆಗಳು',
                                           'ಹಣ್ಣುಗಳು ಕಪ್ಪಾಗಿ ಕೊಳೆಯುವುದು',
                                           'ಕೊಂಬೆಗಳ ಮೇಲೆ ಗಾಯದ ಭಾಗಗಳು',
                                           'ಎಲೆಗಳು ಬಾಡುವುದು'],
                              'solution': ['ಸೋಂಕಿತ ಕೊಂಬೆಗಳನ್ನು ತಕ್ಷಣ ಕತ್ತರಿಸಿ.',
                                           'ತೋಟದಲ್ಲಿರುವ ಸೋಂಕಿತ ಹಣ್ಣುಗಳನ್ನು ತೆಗೆದುಹಾಕಿ.',
                                           'ಬೆಳವಣಿಗೆಯ ಅವಧಿಯಲ್ಲಿ ಶಿಫಾರಸು ಮಾಡಿದ ಶಿಲೀಂಧ್ರನಾಶಕ ಬಳಸಿ.',
                                           'ತೋಟವನ್ನು ಸ್ವಚ್ಛವಾಗಿಡಿ.']}},
 'Apple___Cedar_apple_rust': {'en': {'cause': 'This fungal disease is caused by Gymnosporangium '
                                              'juniperi-virginianae and alternates between cedar and apple '
                                              'trees.',
                                     'symptoms': ['Bright orange spots on leaves',
                                                  'Yellow leaf discoloration',
                                                  'Fruit deformation',
                                                  'Premature leaf fall'],
                                     'solution': ['Remove nearby cedar hosts if practical.',
                                                  'Spray protective fungicides before infection.',
                                                  'Collect and destroy infected leaves.',
                                                  'Grow resistant apple cultivars.']},
                              'kn': {'cause': 'ಈ ಶಿಲೀಂಧ್ರ ರೋಗವು Gymnosporangium juniperi-virginianae '
                                              'ಕಾರಣದಿಂದ ಉಂಟಾಗುತ್ತದೆ ಮತ್ತು ಸೀಡರ್ ಹಾಗೂ ಸೇಬು ಮರಗಳ ನಡುವೆ '
                                              'ಹರಡುತ್ತದೆ.',
                                     'symptoms': ['ಎಲೆಗಳ ಮೇಲೆ ಪ್ರಕಾಶಮಾನ ಕಿತ್ತಳೆ ಬಣ್ಣದ ಕಲೆಗಳು',
                                                  'ಎಲೆಗಳು ಹಳದಿಯಾಗುವುದು',
                                                  'ಹಣ್ಣುಗಳ ಆಕಾರ ಬದಲಾಗುವುದು',
                                                  'ಎಲೆಗಳು ಬೇಗ ಉದುರುವುದು'],
                                     'solution': ['ಸಾಧ್ಯವಾದರೆ ಹತ್ತಿರದ ಸೀಡರ್ ಮರಗಳನ್ನು ತೆಗೆದುಹಾಕಿ.',
                                                  'ಸೋಂಕು ಬರುವ ಮೊದಲು ರಕ್ಷಣಾತ್ಮಕ ಶಿಲೀಂಧ್ರನಾಶಕ ಸಿಂಪಡಿಸಿ.',
                                                  'ಸೋಂಕಿತ ಎಲೆಗಳನ್ನು ಸಂಗ್ರಹಿಸಿ ನಾಶಪಡಿಸಿ.',
                                                  'ರೋಗನಿರೋಧಕ ಸೇಬಿನ ತಳಿಗಳನ್ನು ಬೆಳೆಸಿ.']}},
 'Apple___healthy': {'en': {'cause': 'Healthy plant with no visible disease symptoms.',
                            'symptoms': ['Healthy green leaves',
                                         'No spots or lesions',
                                         'Normal fruit development',
                                         'Strong plant growth'],
                            'solution': ['Continue regular irrigation.',
                                         'Apply balanced fertilizers.',
                                         'Monitor regularly for pests and diseases.',
                                         'Maintain proper orchard hygiene.']},
                     'kn': {'cause': 'ಯಾವುದೇ ಗೋಚರ ರೋಗಲಕ್ಷಣಗಳಿಲ್ಲದ ಆರೋಗ್ಯಕರ ಗಿಡ.',
                            'symptoms': ['ಆರೋಗ್ಯಕರ ಹಸಿರು ಎಲೆಗಳು',
                                         'ಯಾವುದೇ ಕಲೆಗಳು ಅಥವಾ ಗಾಯಗಳಿಲ್ಲ',
                                         'ಹಣ್ಣುಗಳ ಸಾಮಾನ್ಯ ಬೆಳವಣಿಗೆ',
                                         'ಗಿಡದ ಬಲವಾದ ಬೆಳವಣಿಗೆ'],
                            'solution': ['ನಿಯಮಿತವಾಗಿ ನೀರು ಹಾಕುವುದನ್ನು ಮುಂದುವರಿಸಿ.',
                                         'ಸಮತೋಲನ ಗೊಬ್ಬರ ಬಳಸಿ.',
                                         'ಕೀಟಗಳು ಮತ್ತು ರೋಗಗಳಿಗಾಗಿ ನಿಯಮಿತವಾಗಿ ಪರಿಶೀಲಿಸಿ.',
                                         'ತೋಟದ ಸ್ವಚ್ಛತೆಯನ್ನು ಕಾಪಾಡಿ.']}},
 'Blueberry___healthy': {'en': {'cause': 'Healthy blueberry plant.',
                                'symptoms': ['Green healthy foliage',
                                             'Normal berry development',
                                             'No visible disease',
                                             'Healthy stems'],
                                'solution': ['Maintain proper watering schedule.',
                                             'Apply balanced fertilizer when needed.',
                                             'Keep weeds under control.',
                                             'Inspect plants regularly.']},
                         'kn': {'cause': 'ಆರೋಗ್ಯಕರ ಬ್ಲೂಬೆರಿ ಗಿಡ.',
                                'symptoms': ['ಆರೋಗ್ಯಕರ ಹಸಿರು ಎಲೆಗಳು',
                                             'ಬೆರಿಗಳ ಸಾಮಾನ್ಯ ಬೆಳವಣಿಗೆ',
                                             'ಯಾವುದೇ ಗೋಚರ ರೋಗವಿಲ್ಲ',
                                             'ಆರೋಗ್ಯಕರ ಕಾಂಡಗಳು'],
                                'solution': ['ಸರಿಯಾದ ನೀರಾವರಿ ವೇಳಾಪಟ್ಟಿಯನ್ನು ಪಾಲಿಸಿ.',
                                             'ಅಗತ್ಯವಿದ್ದಾಗ ಸಮತೋಲನ ಗೊಬ್ಬರ ಬಳಸಿ.',
                                             'ಕಳೆಗಳನ್ನು ನಿಯಂತ್ರಣದಲ್ಲಿ ಇಡಿ.',
                                             'ಗಿಡಗಳನ್ನು ನಿಯಮಿತವಾಗಿ ಪರಿಶೀಲಿಸಿ.']}},
 'Cherry_(including_sour)___Powdery_mildew': {'en': {'cause': 'Powdery mildew is caused by Podosphaera '
                                                              'species fungi.',
                                                     'symptoms': ['White powdery coating on leaves',
                                                                  'Leaf curling',
                                                                  'Poor fruit growth',
                                                                  'Reduced vigor'],
                                                     'solution': ['Remove infected leaves.',
                                                                  'Apply sulfur or suitable fungicides.',
                                                                  'Improve air circulation through pruning.',
                                                                  'Avoid excessive nitrogen fertilization.']},
                                              'kn': {'cause': 'ಬೂದಿ ರೋಗವು Podosphaera ಜಾತಿಯ ಶಿಲೀಂಧ್ರಗಳಿಂದ '
                                                              'ಉಂಟಾಗುತ್ತದೆ.',
                                                     'symptoms': ['ಎಲೆಗಳ ಮೇಲೆ ಬಿಳಿ ಪುಡಿಯಂತಿರುವ ಪದರ',
                                                                  'ಎಲೆಗಳು ಮಡಚಿಕೊಳ್ಳುವುದು',
                                                                  'ಹಣ್ಣುಗಳ ಬೆಳವಣಿಗೆ ಕಡಿಮೆಯಾಗುವುದು',
                                                                  'ಗಿಡದ ಚೈತನ್ಯ ಕಡಿಮೆಯಾಗುವುದು'],
                                                     'solution': ['ಸೋಂಕಿತ ಎಲೆಗಳನ್ನು ತೆಗೆದುಹಾಕಿ.',
                                                                  'ಗಂಧಕ ಅಥವಾ ಸೂಕ್ತ ಶಿಲೀಂಧ್ರನಾಶಕ ಬಳಸಿ.',
                                                                  'ಕೊಂಬೆಗಳನ್ನು ಕತ್ತರಿಸಿ ಗಾಳಿಯ ಹರಿವು '
                                                                  'ಹೆಚ್ಚಿಸಿ.',
                                                                  'ಅತಿಯಾದ ನೈಟ್ರೋಜನ್ ಗೊಬ್ಬರ ಬಳಕೆಯನ್ನು '
                                                                  'ತಪ್ಪಿಸಿ.']}},
 'Cherry_(including_sour)___healthy': {'en': {'cause': 'Healthy cherry plant.',
                                              'symptoms': ['Dark green leaves',
                                                           'Healthy fruits',
                                                           'Normal flowering',
                                                           'Strong growth'],
                                              'solution': ['Continue routine care.',
                                                           'Water consistently.',
                                                           'Monitor for early disease signs.',
                                                           'Maintain clean orchard conditions.']},
                                       'kn': {'cause': 'ಆರೋಗ್ಯಕರ ಚೆರಿ ಗಿಡ.',
                                              'symptoms': ['ಗಾಢ ಹಸಿರು ಎಲೆಗಳು',
                                                           'ಆರೋಗ್ಯಕರ ಹಣ್ಣುಗಳು',
                                                           'ಸಾಮಾನ್ಯ ಹೂಬಿಡುವಿಕೆ',
                                                           'ಬಲವಾದ ಬೆಳವಣಿಗೆ'],
                                              'solution': ['ನಿಯಮಿತ ಆರೈಕೆಯನ್ನು ಮುಂದುವರಿಸಿ.',
                                                           'ಸರಿಯಾದ ಪ್ರಮಾಣದಲ್ಲಿ ನಿಯಮಿತವಾಗಿ ನೀರು ಹಾಕಿ.',
                                                           'ರೋಗದ ಆರಂಭಿಕ ಲಕ್ಷಣಗಳಿಗಾಗಿ ಗಮನಿಸಿ.',
                                                           'ತೋಟವನ್ನು ಸ್ವಚ್ಛವಾಗಿಡಿ.']}},
 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot': {'en': {'cause': 'Gray leaf spot is caused by '
                                                                        'Cercospora zeae-maydis fungus.',
                                                               'symptoms': ['Long gray rectangular lesions',
                                                                            'Leaf drying',
                                                                            'Reduced photosynthesis',
                                                                            'Lower grain yield'],
                                                               'solution': ['Plant resistant hybrids.',
                                                                            'Apply recommended fungicides.',
                                                                            'Rotate crops annually.',
                                                                            'Remove infected crop residue.']},
                                                        'kn': {'cause': 'ಬೂದು ಎಲೆ ಕಲೆ ರೋಗವು Cercospora '
                                                                        'zeae-maydis ಎಂಬ ಶಿಲೀಂಧ್ರದಿಂದ '
                                                                        'ಉಂಟಾಗುತ್ತದೆ.',
                                                               'symptoms': ['ಎಲೆಗಳ ಮೇಲೆ ಉದ್ದವಾದ ಬೂದು '
                                                                            'ಆಯತಾಕಾರದ ಗಾಯಗಳು',
                                                                            'ಎಲೆಗಳು ಒಣಗುವುದು',
                                                                            'ಪ್ರಕಾಶಸಂಶ್ಲೇಷಣೆ ಕಡಿಮೆಯಾಗುವುದು',
                                                                            'ಧಾನ್ಯದ ಇಳುವರಿ ಕಡಿಮೆಯಾಗುವುದು'],
                                                               'solution': ['ರೋಗನಿರೋಧಕ ಸಂಕರ ತಳಿಗಳನ್ನು '
                                                                            'ಬೆಳೆಸಿ.',
                                                                            'ಶಿಫಾರಸು ಮಾಡಿದ ಶಿಲೀಂಧ್ರನಾಶಕ '
                                                                            'ಬಳಸಿ.',
                                                                            'ಪ್ರತಿ ವರ್ಷ ಬೆಳೆ ಪರಿವರ್ತನೆ ಮಾಡಿ.',
                                                                            'ಸೋಂಕಿತ ಬೆಳೆ ಅವಶೇಷಗಳನ್ನು '
                                                                            'ತೆಗೆದುಹಾಕಿ.']}},
 'Corn_(maize)___Common_rust_': {'en': {'cause': 'Common rust is caused by the fungus Puccinia sorghi.',
                                        'symptoms': ['Small reddish-brown pustules',
                                                     'Yellow leaf spots',
                                                     'Premature leaf death',
                                                     'Reduced plant growth'],
                                        'solution': ['Grow resistant corn varieties.',
                                                     'Apply fungicide if disease is severe.',
                                                     'Monitor fields regularly.',
                                                     'Remove infected plant debris.']},
                                 'kn': {'cause': 'ಸಾಮಾನ್ಯ ತುಕ್ಕು ರೋಗವು Puccinia sorghi ಎಂಬ ಶಿಲೀಂಧ್ರದಿಂದ '
                                                 'ಉಂಟಾಗುತ್ತದೆ.',
                                        'symptoms': ['ಸಣ್ಣ ಕೆಂಪು-ಕಂದು ಬಣ್ಣದ ಗುಳ್ಳೆಗಳು',
                                                     'ಎಲೆಗಳ ಮೇಲೆ ಹಳದಿ ಕಲೆಗಳು',
                                                     'ಎಲೆಗಳು ಬೇಗ ಸಾಯುವುದು',
                                                     'ಗಿಡದ ಬೆಳವಣಿಗೆ ಕಡಿಮೆಯಾಗುವುದು'],
                                        'solution': ['ರೋಗನಿರೋಧಕ ಮೆಕ್ಕೆಜೋಳದ ತಳಿಗಳನ್ನು ಬೆಳೆಸಿ.',
                                                     'ರೋಗ ತೀವ್ರವಾಗಿದ್ದರೆ ಶಿಲೀಂಧ್ರನಾಶಕ ಬಳಸಿ.',
                                                     'ಹೊಲವನ್ನು ನಿಯಮಿತವಾಗಿ ಪರಿಶೀಲಿಸಿ.',
                                                     'ಸೋಂಕಿತ ಗಿಡದ ಅವಶೇಷಗಳನ್ನು ತೆಗೆದುಹಾಕಿ.']}},
 'Corn_(maize)___Northern_Leaf_Blight': {'en': {'cause': 'Northern leaf blight is caused by Exserohilum '
                                                         'turcicum fungus.',
                                                'symptoms': ['Long cigar-shaped lesions',
                                                             'Gray-green leaf spots',
                                                             'Leaf drying',
                                                             'Reduced yield'],
                                                'solution': ['Use resistant hybrids.',
                                                             'Apply fungicides when necessary.',
                                                             'Rotate crops every season.',
                                                             'Destroy infected crop residue.']},
                                         'kn': {'cause': 'ಉತ್ತರ ಎಲೆ ಅಂಗಮಾರಿ ರೋಗವು Exserohilum turcicum ಎಂಬ '
                                                         'ಶಿಲೀಂಧ್ರದಿಂದ ಉಂಟಾಗುತ್ತದೆ.',
                                                'symptoms': ['ಸಿಗಾರ್ ಆಕಾರದ ಉದ್ದವಾದ ಗಾಯಗಳು',
                                                             'ಎಲೆಗಳ ಮೇಲೆ ಬೂದು-ಹಸಿರು ಕಲೆಗಳು',
                                                             'ಎಲೆಗಳು ಒಣಗುವುದು',
                                                             'ಇಳುವರಿ ಕಡಿಮೆಯಾಗುವುದು'],
                                                'solution': ['ರೋಗನಿರೋಧಕ ಸಂಕರ ತಳಿಗಳನ್ನು ಬಳಸಿ.',
                                                             'ಅಗತ್ಯವಿದ್ದಾಗ ಶಿಲೀಂಧ್ರನಾಶಕ ಬಳಸಿ.',
                                                             'ಪ್ರತಿ ಹಂಗಾಮಿನಲ್ಲಿ ಬೆಳೆ ಪರಿವರ್ತನೆ ಮಾಡಿ.',
                                                             'ಸೋಂಕಿತ ಬೆಳೆ ಅವಶೇಷಗಳನ್ನು ನಾಶಪಡಿಸಿ.']}},
 'Corn_(maize)___healthy': {'en': {'cause': 'Healthy corn plant with no visible disease symptoms.',
                                   'symptoms': ['Healthy green leaves',
                                                'Strong upright stem',
                                                'Normal ear development',
                                                'No visible spots or lesions'],
                                   'solution': ['Maintain balanced fertilization.',
                                                'Provide proper irrigation during growth.',
                                                'Inspect plants regularly for pests and diseases.',
                                                'Keep the field free from weeds.']},
                            'kn': {'cause': 'ಯಾವುದೇ ಗೋಚರ ರೋಗಲಕ್ಷಣಗಳಿಲ್ಲದ ಆರೋಗ್ಯಕರ ಮೆಕ್ಕೆಜೋಳದ ಗಿಡ.',
                                   'symptoms': ['ಆರೋಗ್ಯಕರ ಹಸಿರು ಎಲೆಗಳು',
                                                'ಬಲವಾದ ನೇರ ಕಾಂಡ',
                                                'ತೆನೆಯ ಸಾಮಾನ್ಯ ಬೆಳವಣಿಗೆ',
                                                'ಯಾವುದೇ ಗೋಚರ ಕಲೆಗಳು ಅಥವಾ ಗಾಯಗಳಿಲ್ಲ'],
                                   'solution': ['ಸಮತೋಲನ ಗೊಬ್ಬರ ಬಳಸಿ.',
                                                'ಬೆಳವಣಿಗೆಯ ಸಮಯದಲ್ಲಿ ಸರಿಯಾದ ನೀರಾವರಿ ಒದಗಿಸಿ.',
                                                'ಕೀಟಗಳು ಮತ್ತು ರೋಗಗಳಿಗಾಗಿ ಗಿಡಗಳನ್ನು ನಿಯಮಿತವಾಗಿ ಪರಿಶೀಲಿಸಿ.',
                                                'ಹೊಲವನ್ನು ಕಳೆರಹಿತವಾಗಿಡಿ.']}},
 'Grape___Black_rot': {'en': {'cause': 'Black rot is caused by the fungus Guignardia bidwellii.',
                              'symptoms': ['Brown circular spots on leaves',
                                           'Black shriveled fruits',
                                           'Dark lesions on shoots',
                                           'Premature fruit drop'],
                              'solution': ['Remove infected leaves and fruits.',
                                           'Apply recommended fungicides during the growing season.',
                                           'Prune vines to improve air circulation.',
                                           'Keep the vineyard clean by removing plant debris.']},
                       'kn': {'cause': 'ಕಪ್ಪು ಕೊಳೆ ರೋಗವು Guignardia bidwellii ಎಂಬ ಶಿಲೀಂಧ್ರದಿಂದ ಉಂಟಾಗುತ್ತದೆ.',
                              'symptoms': ['ಎಲೆಗಳ ಮೇಲೆ ಕಂದು ವೃತ್ತಾಕಾರದ ಕಲೆಗಳು',
                                           'ಹಣ್ಣುಗಳು ಕಪ್ಪಾಗಿ ಕುಗ್ಗುವುದು',
                                           'ಹೊಸ ಕೊಂಬೆಗಳ ಮೇಲೆ ಗಾಢ ಗಾಯಗಳು',
                                           'ಹಣ್ಣುಗಳು ಬೇಗ ಉದುರುವುದು'],
                              'solution': ['ಸೋಂಕಿತ ಎಲೆಗಳು ಮತ್ತು ಹಣ್ಣುಗಳನ್ನು ತೆಗೆದುಹಾಕಿ.',
                                           'ಬೆಳವಣಿಗೆಯ ಅವಧಿಯಲ್ಲಿ ಶಿಫಾರಸು ಮಾಡಿದ ಶಿಲೀಂಧ್ರನಾಶಕ ಬಳಸಿ.',
                                           'ಗಾಳಿಯ ಹರಿವು ಹೆಚ್ಚಿಸಲು ಬಳ್ಳಿಗಳನ್ನು ಕತ್ತರಿಸಿ.',
                                           'ಗಿಡದ ಅವಶೇಷಗಳನ್ನು ತೆಗೆದು ದ್ರಾಕ್ಷಿತೋಟವನ್ನು ಸ್ವಚ್ಛವಾಗಿಡಿ.']}},
 'Grape___Esca_(Black_Measles)': {'en': {'cause': 'Esca is a fungal trunk disease caused by multiple fungi '
                                                  'including Phaeomoniella chlamydospora.',
                                         'symptoms': ['Tiger-striped leaves',
                                                      'Dark spots on berries',
                                                      'Wood decay',
                                                      'Gradual vine decline'],
                                         'solution': ['Prune infected branches carefully.',
                                                      'Disinfect pruning tools after use.',
                                                      'Remove severely infected vines.',
                                                      'Maintain proper vineyard sanitation.']},
                                  'kn': {'cause': 'ಎಸ್ಕಾ ಎಂಬುದು Phaeomoniella chlamydospora ಸೇರಿದಂತೆ ಹಲವು '
                                                  'ಶಿಲೀಂಧ್ರಗಳಿಂದ ಉಂಟಾಗುವ ಕಾಂಡದ ರೋಗವಾಗಿದೆ.',
                                         'symptoms': ['ಹುಲಿಯ ಪಟ್ಟೆಗಳಂತಿರುವ ಎಲೆಗಳು',
                                                      'ಬೆರಿಗಳ ಮೇಲೆ ಗಾಢ ಕಲೆಗಳು',
                                                      'ಮರದ ಭಾಗ ಕೊಳೆಯುವುದು',
                                                      'ಬಳ್ಳಿ ನಿಧಾನವಾಗಿ ದುರ್ಬಲವಾಗುವುದು'],
                                         'solution': ['ಸೋಂಕಿತ ಕೊಂಬೆಗಳನ್ನು ಎಚ್ಚರಿಕೆಯಿಂದ ಕತ್ತರಿಸಿ.',
                                                      'ಬಳಕೆಯ ನಂತರ ಕತ್ತರಿಸುವ ಸಾಧನಗಳನ್ನು ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಿ.',
                                                      'ತೀವ್ರವಾಗಿ ಸೋಂಕಿತ ಬಳ್ಳಿಗಳನ್ನು ತೆಗೆದುಹಾಕಿ.',
                                                      'ದ್ರಾಕ್ಷಿತೋಟದ ಸ್ವಚ್ಛತೆಯನ್ನು ಕಾಪಾಡಿ.']}},
 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)': {'en': {'cause': 'Leaf blight is caused by the fungus '
                                                                'Pseudocercospora vitis.',
                                                       'symptoms': ['Irregular brown leaf spots',
                                                                    'Yellowing around lesions',
                                                                    'Leaf drying',
                                                                    'Reduced photosynthesis'],
                                                       'solution': ['Remove infected leaves.',
                                                                    'Apply copper-based or recommended '
                                                                    'fungicides.',
                                                                    'Avoid prolonged leaf wetness.',
                                                                    'Maintain proper vine spacing.']},
                                                'kn': {'cause': 'ಎಲೆ ಅಂಗಮಾರಿ ರೋಗವು Pseudocercospora vitis '
                                                                'ಎಂಬ ಶಿಲೀಂಧ್ರದಿಂದ ಉಂಟಾಗುತ್ತದೆ.',
                                                       'symptoms': ['ಎಲೆಗಳ ಮೇಲೆ ಅಸಮ ಕಂದು ಕಲೆಗಳು',
                                                                    'ಗಾಯಗಳ ಸುತ್ತ ಹಳದಿ ಬಣ್ಣ',
                                                                    'ಎಲೆಗಳು ಒಣಗುವುದು',
                                                                    'ಪ್ರಕಾಶಸಂಶ್ಲೇಷಣೆ ಕಡಿಮೆಯಾಗುವುದು'],
                                                       'solution': ['ಸೋಂಕಿತ ಎಲೆಗಳನ್ನು ತೆಗೆದುಹಾಕಿ.',
                                                                    'ತಾಮ್ರ ಆಧಾರಿತ ಅಥವಾ ಶಿಫಾರಸು ಮಾಡಿದ '
                                                                    'ಶಿಲೀಂಧ್ರನಾಶಕ ಬಳಸಿ.',
                                                                    'ಎಲೆಗಳು ದೀರ್ಘಕಾಲ ತೇವವಾಗಿರುವುದನ್ನು '
                                                                    'ತಪ್ಪಿಸಿ.',
                                                                    'ಬಳ್ಳಿಗಳ ನಡುವೆ ಸರಿಯಾದ ಅಂತರ '
                                                                    'ಕಾಯ್ದುಕೊಳ್ಳಿ.']}},
 'Grape___healthy': {'en': {'cause': 'Healthy grapevine with no visible disease symptoms.',
                            'symptoms': ['Healthy green foliage',
                                         'Well-developed grape clusters',
                                         'Strong vine growth',
                                         'No visible disease spots'],
                            'solution': ['Continue regular irrigation and fertilization.',
                                         'Prune vines every season.',
                                         'Monitor regularly for disease symptoms.',
                                         'Maintain vineyard cleanliness.']},
                     'kn': {'cause': 'ಯಾವುದೇ ಗೋಚರ ರೋಗಲಕ್ಷಣಗಳಿಲ್ಲದ ಆರೋಗ್ಯಕರ ದ್ರಾಕ್ಷಿ ಬಳ್ಳಿ.',
                            'symptoms': ['ಆರೋಗ್ಯಕರ ಹಸಿರು ಎಲೆಗಳು',
                                         'ಚೆನ್ನಾಗಿ ಬೆಳೆದ ದ್ರಾಕ್ಷಿ ಗೊಂಚಲುಗಳು',
                                         'ಬಲವಾದ ಬಳ್ಳಿ ಬೆಳವಣಿಗೆ',
                                         'ಯಾವುದೇ ಗೋಚರ ರೋಗದ ಕಲೆಗಳಿಲ್ಲ'],
                            'solution': ['ನಿಯಮಿತ ನೀರಾವರಿ ಮತ್ತು ಗೊಬ್ಬರ ಬಳಕೆಯನ್ನು ಮುಂದುವರಿಸಿ.',
                                         'ಪ್ರತಿ ಹಂಗಾಮಿನಲ್ಲಿ ಬಳ್ಳಿಗಳನ್ನು ಕತ್ತರಿಸಿ.',
                                         'ರೋಗಲಕ್ಷಣಗಳಿಗಾಗಿ ನಿಯಮಿತವಾಗಿ ಪರಿಶೀಲಿಸಿ.',
                                         'ದ್ರಾಕ್ಷಿತೋಟವನ್ನು ಸ್ವಚ್ಛವಾಗಿಡಿ.']}},
 'Orange___Haunglongbing_(Citrus_greening)': {'en': {'cause': 'Citrus greening is caused by Candidatus '
                                                              'Liberibacter bacteria spread by Asian citrus '
                                                              'psyllids.',
                                                     'symptoms': ['Yellow mottled leaves',
                                                                  'Small misshapen fruits',
                                                                  'Bitter fruit taste',
                                                                  'Gradual tree decline'],
                                                     'solution': ['Remove severely infected trees.',
                                                                  'Control citrus psyllids using recommended '
                                                                  'insecticides.',
                                                                  'Use certified disease-free planting '
                                                                  'material.',
                                                                  'Regularly monitor the orchard for early '
                                                                  'symptoms.']},
                                              'kn': {'cause': 'ಸಿಟ್ರಸ್ ಗ್ರೀನಿಂಗ್ ರೋಗವು Candidatus '
                                                              'Liberibacter ಬ್ಯಾಕ್ಟೀರಿಯಾದಿಂದ ಉಂಟಾಗುತ್ತದೆ '
                                                              'ಮತ್ತು ಏಷ್ಯನ್ ಸಿಟ್ರಸ್ ಸೈಲಿಡ್ ಕೀಟಗಳಿಂದ '
                                                              'ಹರಡುತ್ತದೆ.',
                                                     'symptoms': ['ಎಲೆಗಳ ಮೇಲೆ ಅಸಮ ಹಳದಿ ಮಚ್ಚೆಗಳು',
                                                                  'ಸಣ್ಣ ಮತ್ತು ವಕ್ರ ಆಕಾರದ ಹಣ್ಣುಗಳು',
                                                                  'ಹಣ್ಣುಗಳಿಗೆ ಕಹಿ ರುಚಿ',
                                                                  'ಮರ ನಿಧಾನವಾಗಿ ದುರ್ಬಲವಾಗುವುದು'],
                                                     'solution': ['ತೀವ್ರವಾಗಿ ಸೋಂಕಿತ ಮರಗಳನ್ನು ತೆಗೆದುಹಾಕಿ.',
                                                                  'ಶಿಫಾರಸು ಮಾಡಿದ ಕೀಟನಾಶಕಗಳಿಂದ ಸಿಟ್ರಸ್ ಸೈಲಿಡ್ '
                                                                  'ಕೀಟಗಳನ್ನು ನಿಯಂತ್ರಿಸಿ.',
                                                                  'ಪ್ರಮಾಣೀಕೃತ ರೋಗರಹಿತ ನೆಡುವ ಸಾಮಗ್ರಿ ಬಳಸಿ.',
                                                                  'ಆರಂಭಿಕ ಲಕ್ಷಣಗಳಿಗಾಗಿ ತೋಟವನ್ನು ನಿಯಮಿತವಾಗಿ '
                                                                  'ಪರಿಶೀಲಿಸಿ.']}},
 'Peach___Bacterial_spot': {'en': {'cause': 'Bacterial spot is caused by Xanthomonas arboricola pv. pruni.',
                                   'symptoms': ['Small dark spots on leaves',
                                                'Fruit lesions',
                                                'Leaf yellowing',
                                                'Premature leaf drop'],
                                   'solution': ['Remove infected leaves and fruits.',
                                                'Apply copper-based bactericides.',
                                                'Avoid overhead irrigation.',
                                                'Use disease-resistant peach varieties when available.']},
                            'kn': {'cause': 'ಬ್ಯಾಕ್ಟೀರಿಯಾ ಕಲೆ ರೋಗವು Xanthomonas arboricola pv. pruni '
                                            'ಕಾರಣದಿಂದ ಉಂಟಾಗುತ್ತದೆ.',
                                   'symptoms': ['ಎಲೆಗಳ ಮೇಲೆ ಸಣ್ಣ ಗಾಢ ಕಲೆಗಳು',
                                                'ಹಣ್ಣುಗಳ ಮೇಲೆ ಗಾಯದ ಕಲೆಗಳು',
                                                'ಎಲೆಗಳು ಹಳದಿಯಾಗುವುದು',
                                                'ಎಲೆಗಳು ಬೇಗ ಉದುರುವುದು'],
                                   'solution': ['ಸೋಂಕಿತ ಎಲೆಗಳು ಮತ್ತು ಹಣ್ಣುಗಳನ್ನು ತೆಗೆದುಹಾಕಿ.',
                                                'ತಾಮ್ರ ಆಧಾರಿತ ಬ್ಯಾಕ್ಟೀರಿಯಾ ನಾಶಕ ಬಳಸಿ.',
                                                'ಮೇಲಿನಿಂದ ನೀರು ಹಾಕುವುದನ್ನು ತಪ್ಪಿಸಿ.',
                                                'ಲಭ್ಯವಿದ್ದರೆ ರೋಗನಿರೋಧಕ ಪೀಚ್ ತಳಿಗಳನ್ನು ಬಳಸಿ.']}},
 'Peach___healthy': {'en': {'cause': 'Healthy peach tree.',
                            'symptoms': ['Green healthy leaves',
                                         'Normal fruit development',
                                         'Strong branches',
                                         'No visible disease symptoms'],
                            'solution': ['Maintain regular irrigation.',
                                         'Apply balanced fertilizers.',
                                         'Prune trees annually.',
                                         'Inspect regularly for pests and diseases.']},
                     'kn': {'cause': 'ಆರೋಗ್ಯಕರ ಪೀಚ್ ಮರ.',
                            'symptoms': ['ಆರೋಗ್ಯಕರ ಹಸಿರು ಎಲೆಗಳು',
                                         'ಹಣ್ಣುಗಳ ಸಾಮಾನ್ಯ ಬೆಳವಣಿಗೆ',
                                         'ಬಲವಾದ ಕೊಂಬೆಗಳು',
                                         'ಯಾವುದೇ ಗೋಚರ ರೋಗಲಕ್ಷಣಗಳಿಲ್ಲ'],
                            'solution': ['ನಿಯಮಿತ ನೀರಾವರಿ ಒದಗಿಸಿ.',
                                         'ಸಮತೋಲನ ಗೊಬ್ಬರ ಬಳಸಿ.',
                                         'ಪ್ರತಿ ವರ್ಷ ಮರವನ್ನು ಕತ್ತರಿಸಿ.',
                                         'ಕೀಟಗಳು ಮತ್ತು ರೋಗಗಳಿಗಾಗಿ ನಿಯಮಿತವಾಗಿ ಪರಿಶೀಲಿಸಿ.']}},
 'Pepper,_bell___Bacterial_spot': {'en': {'cause': 'Bacterial spot is caused by Xanthomonas species.',
                                          'symptoms': ['Small water-soaked leaf spots',
                                                       'Dark fruit lesions',
                                                       'Leaf yellowing',
                                                       'Reduced fruit quality'],
                                          'solution': ['Remove infected plants and leaves.',
                                                       'Apply copper-based bactericides.',
                                                       'Avoid working with wet plants.',
                                                       'Practice crop rotation.']},
                                   'kn': {'cause': 'ಬ್ಯಾಕ್ಟೀರಿಯಾ ಕಲೆ ರೋಗವು Xanthomonas ಜಾತಿಯ '
                                                   'ಬ್ಯಾಕ್ಟೀರಿಯಾದಿಂದ ಉಂಟಾಗುತ್ತದೆ.',
                                          'symptoms': ['ಎಲೆಗಳ ಮೇಲೆ ನೀರು ನೆನೆದಂತಿರುವ ಸಣ್ಣ ಕಲೆಗಳು',
                                                       'ಹಣ್ಣುಗಳ ಮೇಲೆ ಗಾಢ ಗಾಯಗಳು',
                                                       'ಎಲೆಗಳು ಹಳದಿಯಾಗುವುದು',
                                                       'ಹಣ್ಣಿನ ಗುಣಮಟ್ಟ ಕಡಿಮೆಯಾಗುವುದು'],
                                          'solution': ['ಸೋಂಕಿತ ಗಿಡಗಳು ಮತ್ತು ಎಲೆಗಳನ್ನು ತೆಗೆದುಹಾಕಿ.',
                                                       'ತಾಮ್ರ ಆಧಾರಿತ ಬ್ಯಾಕ್ಟೀರಿಯಾ ನಾಶಕ ಬಳಸಿ.',
                                                       'ತೇವವಾದ ಗಿಡಗಳ ನಡುವೆ ಕೆಲಸ ಮಾಡುವುದನ್ನು ತಪ್ಪಿಸಿ.',
                                                       'ಬೆಳೆ ಪರಿವರ್ತನೆ ಅನುಸರಿಸಿ.']}},
 'Pepper,_bell___healthy': {'en': {'cause': 'Healthy bell pepper plant.',
                                   'symptoms': ['Healthy green leaves',
                                                'Good fruit development',
                                                'Strong stem',
                                                'No visible disease symptoms'],
                                   'solution': ['Provide balanced nutrition.',
                                                'Water consistently without overwatering.',
                                                'Inspect plants weekly.',
                                                'Keep the growing area clean.']},
                            'kn': {'cause': 'ಆರೋಗ್ಯಕರ ದೊಣ್ಣೆ ಮೆಣಸಿನಕಾಯಿ ಗಿಡ.',
                                   'symptoms': ['ಆರೋಗ್ಯಕರ ಹಸಿರು ಎಲೆಗಳು',
                                                'ಹಣ್ಣುಗಳ ಉತ್ತಮ ಬೆಳವಣಿಗೆ',
                                                'ಬಲವಾದ ಕಾಂಡ',
                                                'ಯಾವುದೇ ಗೋಚರ ರೋಗಲಕ್ಷಣಗಳಿಲ್ಲ'],
                                   'solution': ['ಸಮತೋಲನ ಪೋಷಕಾಂಶ ಒದಗಿಸಿ.',
                                                'ಹೆಚ್ಚು ನೀರು ಹಾಕದೆ ನಿಯಮಿತವಾಗಿ ನೀರು ಹಾಕಿ.',
                                                'ಪ್ರತಿ ವಾರ ಗಿಡಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.',
                                                'ಬೆಳೆ ಪ್ರದೇಶವನ್ನು ಸ್ವಚ್ಛವಾಗಿಡಿ.']}},
 'Potato___Early_blight': {'en': {'cause': 'Early blight is caused by the fungus Alternaria solani, which '
                                           'spreads in warm and humid conditions.',
                                  'symptoms': ['Brown circular spots with concentric rings on leaves',
                                               'Yellowing of older leaves',
                                               'Premature leaf drop',
                                               'Reduced tuber yield'],
                                  'solution': ['Remove and destroy infected leaves immediately.',
                                               'Spray recommended fungicides such as Mancozeb or '
                                               'Chlorothalonil.',
                                               'Practice crop rotation for at least two years.',
                                               'Avoid overhead irrigation and maintain field sanitation.']},
                           'kn': {'cause': 'ಆರಂಭಿಕ ಅಂಗಮಾರಿ ರೋಗವು Alternaria solani ಎಂಬ ಶಿಲೀಂಧ್ರದಿಂದ '
                                           'ಉಂಟಾಗುತ್ತದೆ. ಇದು ಬಿಸಿ ಮತ್ತು ತೇವವಾದ ಪರಿಸ್ಥಿತಿಯಲ್ಲಿ ಹರಡುತ್ತದೆ.',
                                  'symptoms': ['ಎಲೆಗಳ ಮೇಲೆ ವಲಯಗಳಿರುವ ಕಂದು ವೃತ್ತಾಕಾರದ ಕಲೆಗಳು',
                                               'ಹಳೆಯ ಎಲೆಗಳು ಹಳದಿಯಾಗುವುದು',
                                               'ಎಲೆಗಳು ಬೇಗ ಉದುರುವುದು',
                                               'ಗೆಡ್ಡೆಗಳ ಇಳುವರಿ ಕಡಿಮೆಯಾಗುವುದು'],
                                  'solution': ['ಸೋಂಕಿತ ಎಲೆಗಳನ್ನು ತಕ್ಷಣ ತೆಗೆದು ನಾಶಪಡಿಸಿ.',
                                               'ಮ್ಯಾಂಕೋಜೆಬ್ ಅಥವಾ ಕ್ಲೋರೋಥಾಲೊನಿಲ್\u200cನಂತಹ ಶಿಫಾರಸು ಮಾಡಿದ '
                                               'ಶಿಲೀಂಧ್ರನಾಶಕ ಸಿಂಪಡಿಸಿ.',
                                               'ಕನಿಷ್ಠ ಎರಡು ವರ್ಷ ಬೆಳೆ ಪರಿವರ್ತನೆ ಅನುಸರಿಸಿ.',
                                               'ಮೇಲಿನಿಂದ ನೀರು ಹಾಕುವುದನ್ನು ತಪ್ಪಿಸಿ ಮತ್ತು ಹೊಲವನ್ನು '
                                               'ಸ್ವಚ್ಛವಾಗಿಡಿ.']}},
 'Potato___Late_blight': {'en': {'cause': 'Late blight is caused by Phytophthora infestans, a destructive '
                                          'pathogen that thrives in cool and wet weather.',
                                 'symptoms': ['Large dark brown or black lesions on leaves',
                                              'White fungal growth under infected leaves',
                                              'Rapid wilting and collapse of foliage',
                                              'Brown rotting of potato tubers'],
                                 'solution': ['Remove infected plants and destroy them away from the field.',
                                              'Apply fungicides such as Metalaxyl or Mancozeb as '
                                              'recommended.',
                                              'Avoid excessive moisture and improve air circulation.',
                                              'Use certified disease-free seed potatoes.']},
                          'kn': {'cause': 'ತಡ ಅಂಗಮಾರಿ ರೋಗವು Phytophthora infestans ಎಂಬ ವಿನಾಶಕಾರಿ ರೋಗಕಾರಕದಿಂದ '
                                          'ಉಂಟಾಗುತ್ತದೆ. ಇದು ತಂಪು ಮತ್ತು ತೇವವಾದ ಹವಾಮಾನದಲ್ಲಿ ವೇಗವಾಗಿ '
                                          'ಬೆಳೆಯುತ್ತದೆ.',
                                 'symptoms': ['ಎಲೆಗಳ ಮೇಲೆ ದೊಡ್ಡ ಗಾಢ ಕಂದು ಅಥವಾ ಕಪ್ಪು ಗಾಯಗಳು',
                                              'ಸೋಂಕಿತ ಎಲೆಗಳ ಕೆಳಭಾಗದಲ್ಲಿ ಬಿಳಿ ಶಿಲೀಂಧ್ರ ಬೆಳವಣಿಗೆ',
                                              'ಎಲೆಗಳು ವೇಗವಾಗಿ ಬಾಡಿ ಕುಸಿಯುವುದು',
                                              'ಆಲೂಗಡ್ಡೆ ಗೆಡ್ಡೆಗಳು ಕಂದು ಬಣ್ಣಕ್ಕೆ ತಿರುಗಿ ಕೊಳೆಯುವುದು'],
                                 'solution': ['ಸೋಂಕಿತ ಗಿಡಗಳನ್ನು ತೆಗೆದು ಹೊಲದಿಂದ ದೂರದಲ್ಲಿ ನಾಶಪಡಿಸಿ.',
                                              'ಶಿಫಾರಸಿನಂತೆ ಮೆಟಾಲಾಕ್ಸಿಲ್ ಅಥವಾ ಮ್ಯಾಂಕೋಜೆಬ್ ಶಿಲೀಂಧ್ರನಾಶಕ ಬಳಸಿ.',
                                              'ಅತಿಯಾದ ತೇವವನ್ನು ತಪ್ಪಿಸಿ ಮತ್ತು ಗಾಳಿಯ ಹರಿವು ಹೆಚ್ಚಿಸಿ.',
                                              'ಪ್ರಮಾಣೀಕೃತ ರೋಗರಹಿತ ಬೀಜ ಆಲೂಗಡ್ಡೆ ಬಳಸಿ.']}},
 'Potato___healthy': {'en': {'cause': 'Healthy potato plant with no visible disease symptoms.',
                             'symptoms': ['Healthy green leaves',
                                          'Strong upright stems',
                                          'Normal tuber development',
                                          'No visible spots or lesions'],
                             'solution': ['Continue balanced fertilization.',
                                          'Maintain proper irrigation schedule.',
                                          'Inspect plants regularly for pests and diseases.',
                                          'Keep the field clean and weed-free.']},
                      'kn': {'cause': 'ಯಾವುದೇ ಗೋಚರ ರೋಗಲಕ್ಷಣಗಳಿಲ್ಲದ ಆರೋಗ್ಯಕರ ಆಲೂಗಡ್ಡೆ ಗಿಡ.',
                             'symptoms': ['ಆರೋಗ್ಯಕರ ಹಸಿರು ಎಲೆಗಳು',
                                          'ಬಲವಾದ ನೇರ ಕಾಂಡಗಳು',
                                          'ಗೆಡ್ಡೆಗಳ ಸಾಮಾನ್ಯ ಬೆಳವಣಿಗೆ',
                                          'ಯಾವುದೇ ಗೋಚರ ಕಲೆಗಳು ಅಥವಾ ಗಾಯಗಳಿಲ್ಲ'],
                             'solution': ['ಸಮತೋಲನ ಗೊಬ್ಬರ ಬಳಕೆಯನ್ನು ಮುಂದುವರಿಸಿ.',
                                          'ಸರಿಯಾದ ನೀರಾವರಿ ವೇಳಾಪಟ್ಟಿಯನ್ನು ಪಾಲಿಸಿ.',
                                          'ಕೀಟಗಳು ಮತ್ತು ರೋಗಗಳಿಗಾಗಿ ಗಿಡಗಳನ್ನು ನಿಯಮಿತವಾಗಿ ಪರಿಶೀಲಿಸಿ.',
                                          'ಹೊಲವನ್ನು ಸ್ವಚ್ಛ ಮತ್ತು ಕಳೆರಹಿತವಾಗಿಡಿ.']}},
 'Raspberry___healthy': {'en': {'cause': 'Healthy raspberry plant.',
                                'symptoms': ['Healthy green foliage',
                                             'Strong canes',
                                             'Normal fruit production',
                                             'No visible disease symptoms'],
                                'solution': ['Water consistently during fruit development.',
                                             'Prune old canes after harvest.',
                                             'Maintain clean growing conditions.',
                                             'Monitor regularly for pests and diseases.']},
                         'kn': {'cause': 'ಆರೋಗ್ಯಕರ ರಾಸ್ಪ್ಬೆರಿ ಗಿಡ.',
                                'symptoms': ['ಆರೋಗ್ಯಕರ ಹಸಿರು ಎಲೆಗಳು',
                                             'ಬಲವಾದ ಕಾಂಡಗಳು',
                                             'ಹಣ್ಣುಗಳ ಸಾಮಾನ್ಯ ಉತ್ಪಾದನೆ',
                                             'ಯಾವುದೇ ಗೋಚರ ರೋಗಲಕ್ಷಣಗಳಿಲ್ಲ'],
                                'solution': ['ಹಣ್ಣು ಬೆಳೆಯುವ ಸಮಯದಲ್ಲಿ ನಿಯಮಿತವಾಗಿ ನೀರು ಹಾಕಿ.',
                                             'ಕೊಯ್ಲಿನ ನಂತರ ಹಳೆಯ ಕಾಂಡಗಳನ್ನು ಕತ್ತರಿಸಿ.',
                                             'ಬೆಳೆ ಪ್ರದೇಶವನ್ನು ಸ್ವಚ್ಛವಾಗಿಡಿ.',
                                             'ಕೀಟಗಳು ಮತ್ತು ರೋಗಗಳಿಗಾಗಿ ನಿಯಮಿತವಾಗಿ ಪರಿಶೀಲಿಸಿ.']}},
 'Soybean___healthy': {'en': {'cause': 'Healthy soybean plant.',
                              'symptoms': ['Uniform green leaves',
                                           'Healthy pods',
                                           'Strong stem growth',
                                           'No visible disease symptoms'],
                              'solution': ['Apply balanced fertilizers based on soil testing.',
                                           'Provide proper irrigation when necessary.',
                                           'Control weeds regularly.',
                                           'Inspect crops periodically for early disease detection.']},
                       'kn': {'cause': 'ಆರೋಗ್ಯಕರ ಸೋಯಾಬೀನ್ ಗಿಡ.',
                              'symptoms': ['ಒಂದೇ ರೀತಿಯ ಹಸಿರು ಎಲೆಗಳು',
                                           'ಆರೋಗ್ಯಕರ ಕಾಯಿಗಳು',
                                           'ಬಲವಾದ ಕಾಂಡದ ಬೆಳವಣಿಗೆ',
                                           'ಯಾವುದೇ ಗೋಚರ ರೋಗಲಕ್ಷಣಗಳಿಲ್ಲ'],
                              'solution': ['ಮಣ್ಣಿನ ಪರೀಕ್ಷೆಯ ಆಧಾರದಲ್ಲಿ ಸಮತೋಲನ ಗೊಬ್ಬರ ಬಳಸಿ.',
                                           'ಅಗತ್ಯವಿದ್ದಾಗ ಸರಿಯಾದ ನೀರಾವರಿ ಒದಗಿಸಿ.',
                                           'ಕಳೆಗಳನ್ನು ನಿಯಮಿತವಾಗಿ ನಿಯಂತ್ರಿಸಿ.',
                                           'ರೋಗವನ್ನು ಬೇಗ ಪತ್ತೆಹಚ್ಚಲು ಬೆಳೆಗಳನ್ನು ಕಾಲಕಾಲಕ್ಕೆ ಪರಿಶೀಲಿಸಿ.']}},
 'Squash___Powdery_mildew': {'en': {'cause': 'Powdery mildew is caused by fungal pathogens such as '
                                             'Podosphaera xanthii.',
                                    'symptoms': ['White powder-like patches on leaves',
                                                 'Yellowing of leaves',
                                                 'Premature leaf drying',
                                                 'Reduced fruit quality'],
                                    'solution': ['Remove infected leaves to reduce disease spread.',
                                                 'Apply sulfur or recommended fungicides.',
                                                 'Increase spacing to improve air circulation.',
                                                 'Avoid excessive nitrogen fertilization.']},
                             'kn': {'cause': 'ಬೂದಿ ರೋಗವು Podosphaera xanthii ಮುಂತಾದ ಶಿಲೀಂಧ್ರ ರೋಗಕಾರಕಗಳಿಂದ '
                                             'ಉಂಟಾಗುತ್ತದೆ.',
                                    'symptoms': ['ಎಲೆಗಳ ಮೇಲೆ ಬಿಳಿ ಪುಡಿಯಂತಿರುವ ಮಚ್ಚೆಗಳು',
                                                 'ಎಲೆಗಳು ಹಳದಿಯಾಗುವುದು',
                                                 'ಎಲೆಗಳು ಬೇಗ ಒಣಗುವುದು',
                                                 'ಹಣ್ಣಿನ ಗುಣಮಟ್ಟ ಕಡಿಮೆಯಾಗುವುದು'],
                                    'solution': ['ರೋಗ ಹರಡುವಿಕೆಯನ್ನು ಕಡಿಮೆ ಮಾಡಲು ಸೋಂಕಿತ ಎಲೆಗಳನ್ನು ತೆಗೆದುಹಾಕಿ.',
                                                 'ಗಂಧಕ ಅಥವಾ ಶಿಫಾರಸು ಮಾಡಿದ ಶಿಲೀಂಧ್ರನಾಶಕ ಬಳಸಿ.',
                                                 'ಗಾಳಿಯ ಹರಿವು ಹೆಚ್ಚಿಸಲು ಗಿಡಗಳ ನಡುವಿನ ಅಂತರ ಹೆಚ್ಚಿಸಿ.',
                                                 'ಅತಿಯಾದ ನೈಟ್ರೋಜನ್ ಗೊಬ್ಬರ ಬಳಕೆಯನ್ನು ತಪ್ಪಿಸಿ.']}},
 'Strawberry___Leaf_scorch': {'en': {'cause': 'Leaf scorch is caused by the fungus Diplocarpon earlianum.',
                                     'symptoms': ['Small purple spots on leaves',
                                                  'Brown scorched leaf edges',
                                                  'Drying of leaves',
                                                  'Reduced plant vigor'],
                                     'solution': ['Remove infected leaves and plant debris.',
                                                  'Apply recommended fungicides when necessary.',
                                                  'Avoid overhead irrigation.',
                                                  'Maintain proper spacing for better airflow.']},
                              'kn': {'cause': 'ಎಲೆ ಸುಡುವ ರೋಗವು Diplocarpon earlianum ಎಂಬ ಶಿಲೀಂಧ್ರದಿಂದ '
                                              'ಉಂಟಾಗುತ್ತದೆ.',
                                     'symptoms': ['ಎಲೆಗಳ ಮೇಲೆ ಸಣ್ಣ ನೇರಳೆ ಕಲೆಗಳು',
                                                  'ಎಲೆಗಳ ಅಂಚುಗಳು ಕಂದು ಬಣ್ಣಕ್ಕೆ ತಿರುಗಿ ಸುಟ್ಟಂತಾಗುವುದು',
                                                  'ಎಲೆಗಳು ಒಣಗುವುದು',
                                                  'ಗಿಡದ ಚೈತನ್ಯ ಕಡಿಮೆಯಾಗುವುದು'],
                                     'solution': ['ಸೋಂಕಿತ ಎಲೆಗಳು ಮತ್ತು ಗಿಡದ ಅವಶೇಷಗಳನ್ನು ತೆಗೆದುಹಾಕಿ.',
                                                  'ಅಗತ್ಯವಿದ್ದಾಗ ಶಿಫಾರಸು ಮಾಡಿದ ಶಿಲೀಂಧ್ರನಾಶಕ ಬಳಸಿ.',
                                                  'ಮೇಲಿನಿಂದ ನೀರು ಹಾಕುವುದನ್ನು ತಪ್ಪಿಸಿ.',
                                                  'ಉತ್ತಮ ಗಾಳಿಯ ಹರಿವಿಗಾಗಿ ಸರಿಯಾದ ಅಂತರ ಕಾಯ್ದುಕೊಳ್ಳಿ.']}},
 'Strawberry___healthy': {'en': {'cause': 'Healthy strawberry plant.',
                                 'symptoms': ['Bright green leaves',
                                              'Healthy flowers and fruits',
                                              'Strong runners',
                                              'No visible disease symptoms'],
                                 'solution': ['Maintain proper irrigation.',
                                              'Apply balanced fertilizers.',
                                              'Remove weeds regularly.',
                                              'Inspect plants periodically for early disease detection.']},
                          'kn': {'cause': 'ಆರೋಗ್ಯಕರ ಸ್ಟ್ರಾಬೆರಿ ಗಿಡ.',
                                 'symptoms': ['ಪ್ರಕಾಶಮಾನ ಹಸಿರು ಎಲೆಗಳು',
                                              'ಆರೋಗ್ಯಕರ ಹೂಗಳು ಮತ್ತು ಹಣ್ಣುಗಳು',
                                              'ಬಲವಾದ ರನ್ನರ್\u200cಗಳು',
                                              'ಯಾವುದೇ ಗೋಚರ ರೋಗಲಕ್ಷಣಗಳಿಲ್ಲ'],
                                 'solution': ['ಸರಿಯಾದ ನೀರಾವರಿ ಒದಗಿಸಿ.',
                                              'ಸಮತೋಲನ ಗೊಬ್ಬರ ಬಳಸಿ.',
                                              'ಕಳೆಗಳನ್ನು ನಿಯಮಿತವಾಗಿ ತೆಗೆದುಹಾಕಿ.',
                                              'ರೋಗವನ್ನು ಬೇಗ ಪತ್ತೆಹಚ್ಚಲು ಗಿಡಗಳನ್ನು ಕಾಲಕಾಲಕ್ಕೆ ಪರಿಶೀಲಿಸಿ.']}},
 'Tomato___Bacterial_spot': {'en': {'cause': 'Bacterial spot is caused by Xanthomonas species and spreads '
                                             'rapidly in warm, humid conditions.',
                                    'symptoms': ['Small dark water-soaked spots on leaves',
                                                 'Brown lesions on fruits',
                                                 'Yellowing of leaves',
                                                 'Premature leaf drop'],
                                    'solution': ['Remove infected leaves and fruits.',
                                                 'Apply copper-based bactericides.',
                                                 'Avoid overhead irrigation.',
                                                 'Use certified disease-free seeds.']},
                             'kn': {'cause': 'ಬ್ಯಾಕ್ಟೀರಿಯಾ ಕಲೆ ರೋಗವು Xanthomonas ಜಾತಿಯ ಬ್ಯಾಕ್ಟೀರಿಯಾದಿಂದ '
                                             'ಉಂಟಾಗುತ್ತದೆ ಮತ್ತು ಬಿಸಿ, ತೇವವಾದ ಪರಿಸ್ಥಿತಿಯಲ್ಲಿ ವೇಗವಾಗಿ '
                                             'ಹರಡುತ್ತದೆ.',
                                    'symptoms': ['ಎಲೆಗಳ ಮೇಲೆ ನೀರು ನೆನೆದಂತಿರುವ ಸಣ್ಣ ಗಾಢ ಕಲೆಗಳು',
                                                 'ಹಣ್ಣುಗಳ ಮೇಲೆ ಕಂದು ಗಾಯಗಳು',
                                                 'ಎಲೆಗಳು ಹಳದಿಯಾಗುವುದು',
                                                 'ಎಲೆಗಳು ಬೇಗ ಉದುರುವುದು'],
                                    'solution': ['ಸೋಂಕಿತ ಎಲೆಗಳು ಮತ್ತು ಹಣ್ಣುಗಳನ್ನು ತೆಗೆದುಹಾಕಿ.',
                                                 'ತಾಮ್ರ ಆಧಾರಿತ ಬ್ಯಾಕ್ಟೀರಿಯಾ ನಾಶಕ ಬಳಸಿ.',
                                                 'ಮೇಲಿನಿಂದ ನೀರು ಹಾಕುವುದನ್ನು ತಪ್ಪಿಸಿ.',
                                                 'ಪ್ರಮಾಣೀಕೃತ ರೋಗರಹಿತ ಬೀಜಗಳನ್ನು ಬಳಸಿ.']}},
 'Tomato___Early_blight': {'en': {'cause': 'Early blight is caused by the fungus Alternaria solani.',
                                  'symptoms': ['Brown circular spots with concentric rings',
                                               'Yellowing of lower leaves',
                                               'Leaf drying',
                                               'Reduced fruit production'],
                                  'solution': ['Remove infected leaves immediately.',
                                               'Apply Mancozeb or Chlorothalonil fungicide.',
                                               'Practice crop rotation.',
                                               'Keep the field clean and weed-free.']},
                           'kn': {'cause': 'ಆರಂಭಿಕ ಅಂಗಮಾರಿ ರೋಗವು Alternaria solani ಎಂಬ ಶಿಲೀಂಧ್ರದಿಂದ '
                                           'ಉಂಟಾಗುತ್ತದೆ.',
                                  'symptoms': ['ವಲಯಗಳಿರುವ ಕಂದು ವೃತ್ತಾಕಾರದ ಕಲೆಗಳು',
                                               'ಕೆಳಗಿನ ಎಲೆಗಳು ಹಳದಿಯಾಗುವುದು',
                                               'ಎಲೆಗಳು ಒಣಗುವುದು',
                                               'ಹಣ್ಣಿನ ಉತ್ಪಾದನೆ ಕಡಿಮೆಯಾಗುವುದು'],
                                  'solution': ['ಸೋಂಕಿತ ಎಲೆಗಳನ್ನು ತಕ್ಷಣ ತೆಗೆದುಹಾಕಿ.',
                                               'ಮ್ಯಾಂಕೋಜೆಬ್ ಅಥವಾ ಕ್ಲೋರೋಥಾಲೊನಿಲ್ ಶಿಲೀಂಧ್ರನಾಶಕ ಬಳಸಿ.',
                                               'ಬೆಳೆ ಪರಿವರ್ತನೆ ಅನುಸರಿಸಿ.',
                                               'ಹೊಲವನ್ನು ಸ್ವಚ್ಛ ಮತ್ತು ಕಳೆರಹಿತವಾಗಿಡಿ.']}},
 'Tomato___Late_blight': {'en': {'cause': 'Late blight is caused by Phytophthora infestans and spreads '
                                          'quickly during cool, wet weather.',
                                 'symptoms': ['Large brown or black leaf lesions',
                                              'White fungal growth beneath leaves',
                                              'Fruit rot',
                                              'Rapid plant collapse'],
                                 'solution': ['Destroy infected plants immediately.',
                                              'Apply Metalaxyl or Mancozeb fungicide.',
                                              'Improve field drainage and airflow.',
                                              'Use certified healthy seedlings.']},
                          'kn': {'cause': 'ತಡ ಅಂಗಮಾರಿ ರೋಗವು Phytophthora infestans ಕಾರಣದಿಂದ ಉಂಟಾಗುತ್ತದೆ '
                                          'ಮತ್ತು ತಂಪು, ತೇವವಾದ ಹವಾಮಾನದಲ್ಲಿ ವೇಗವಾಗಿ ಹರಡುತ್ತದೆ.',
                                 'symptoms': ['ಎಲೆಗಳ ಮೇಲೆ ದೊಡ್ಡ ಕಂದು ಅಥವಾ ಕಪ್ಪು ಗಾಯಗಳು',
                                              'ಎಲೆಗಳ ಕೆಳಭಾಗದಲ್ಲಿ ಬಿಳಿ ಶಿಲೀಂಧ್ರ ಬೆಳವಣಿಗೆ',
                                              'ಹಣ್ಣು ಕೊಳೆಯುವುದು',
                                              'ಗಿಡ ವೇಗವಾಗಿ ಕುಸಿಯುವುದು'],
                                 'solution': ['ಸೋಂಕಿತ ಗಿಡಗಳನ್ನು ತಕ್ಷಣ ನಾಶಪಡಿಸಿ.',
                                              'ಮೆಟಾಲಾಕ್ಸಿಲ್ ಅಥವಾ ಮ್ಯಾಂಕೋಜೆಬ್ ಶಿಲೀಂಧ್ರನಾಶಕ ಬಳಸಿ.',
                                              'ಹೊಲದ ನೀರು ಹರಿವು ಮತ್ತು ಗಾಳಿಯ ಹರಿವು ಸುಧಾರಿಸಿ.',
                                              'ಪ್ರಮಾಣೀಕೃತ ಆರೋಗ್ಯಕರ ಸಸಿಗಳನ್ನು ಬಳಸಿ.']}},
 'Tomato___Leaf_Mold': {'en': {'cause': 'Leaf mold is caused by the fungus Passalora fulva.',
                               'symptoms': ['Yellow patches on upper leaf surface',
                                            'Olive-green mold beneath leaves',
                                            'Leaf curling',
                                            'Reduced plant vigor'],
                               'solution': ['Reduce humidity inside the crop area.',
                                            'Remove infected leaves.',
                                            'Apply recommended fungicides.',
                                            'Maintain good air circulation.']},
                        'kn': {'cause': 'ಎಲೆ ಬೂಷ್ಟು ರೋಗವು Passalora fulva ಎಂಬ ಶಿಲೀಂಧ್ರದಿಂದ ಉಂಟಾಗುತ್ತದೆ.',
                               'symptoms': ['ಎಲೆಯ ಮೇಲ್ಮೈಯಲ್ಲಿ ಹಳದಿ ಮಚ್ಚೆಗಳು',
                                            'ಎಲೆಗಳ ಕೆಳಭಾಗದಲ್ಲಿ ಆಲಿವ್-ಹಸಿರು ಬೂಷ್ಟು',
                                            'ಎಲೆಗಳು ಮಡಚಿಕೊಳ್ಳುವುದು',
                                            'ಗಿಡದ ಚೈತನ್ಯ ಕಡಿಮೆಯಾಗುವುದು'],
                               'solution': ['ಬೆಳೆ ಪ್ರದೇಶದ ತೇವಾಂಶವನ್ನು ಕಡಿಮೆ ಮಾಡಿ.',
                                            'ಸೋಂಕಿತ ಎಲೆಗಳನ್ನು ತೆಗೆದುಹಾಕಿ.',
                                            'ಶಿಫಾರಸು ಮಾಡಿದ ಶಿಲೀಂಧ್ರನಾಶಕ ಬಳಸಿ.',
                                            'ಉತ್ತಮ ಗಾಳಿಯ ಹರಿವು ಕಾಪಾಡಿ.']}},
 'Tomato___Septoria_leaf_spot': {'en': {'cause': 'Septoria leaf spot is caused by Septoria lycopersici '
                                                 'fungus.',
                                        'symptoms': ['Small circular spots with gray centers',
                                                     'Yellowing of leaves',
                                                     'Premature leaf drop',
                                                     'Reduced yield'],
                                        'solution': ['Remove infected leaves.',
                                                     'Apply fungicides as recommended.',
                                                     'Avoid overhead watering.',
                                                     'Rotate crops every season.']},
                                 'kn': {'cause': 'ಸೆಪ್ಟೋರಿಯಾ ಎಲೆ ಕಲೆ ರೋಗವು Septoria lycopersici ಎಂಬ '
                                                 'ಶಿಲೀಂಧ್ರದಿಂದ ಉಂಟಾಗುತ್ತದೆ.',
                                        'symptoms': ['ಬೂದು ಮಧ್ಯಭಾಗವಿರುವ ಸಣ್ಣ ವೃತ್ತಾಕಾರದ ಕಲೆಗಳು',
                                                     'ಎಲೆಗಳು ಹಳದಿಯಾಗುವುದು',
                                                     'ಎಲೆಗಳು ಬೇಗ ಉದುರುವುದು',
                                                     'ಇಳುವರಿ ಕಡಿಮೆಯಾಗುವುದು'],
                                        'solution': ['ಸೋಂಕಿತ ಎಲೆಗಳನ್ನು ತೆಗೆದುಹಾಕಿ.',
                                                     'ಶಿಫಾರಸಿನಂತೆ ಶಿಲೀಂಧ್ರನಾಶಕ ಬಳಸಿ.',
                                                     'ಮೇಲಿನಿಂದ ನೀರು ಹಾಕುವುದನ್ನು ತಪ್ಪಿಸಿ.',
                                                     'ಪ್ರತಿ ಹಂಗಾಮಿನಲ್ಲಿ ಬೆಳೆ ಪರಿವರ್ತನೆ ಮಾಡಿ.']}},
 'Tomato___Spider_mites Two-spotted_spider_mite': {'en': {'cause': 'This damage is caused by two-spotted '
                                                                   'spider mites feeding on leaf sap.',
                                                          'symptoms': ['Tiny yellow specks on leaves',
                                                                       'Fine webbing under leaves',
                                                                       'Leaf bronzing',
                                                                       'Leaf drying'],
                                                          'solution': ['Spray miticides if infestation is '
                                                                       'severe.',
                                                                       'Increase humidity around plants when '
                                                                       'appropriate.',
                                                                       'Remove heavily infested leaves.',
                                                                       'Encourage natural predators like '
                                                                       'ladybugs.']},
                                                   'kn': {'cause': 'ಎರಡು ಮಚ್ಚೆಯ ಜೇಡ ಹುಳುಗಳು ಎಲೆಯ ರಸವನ್ನು '
                                                                   'ಹೀರುವುದರಿಂದ ಈ ಹಾನಿ ಉಂಟಾಗುತ್ತದೆ.',
                                                          'symptoms': ['ಎಲೆಗಳ ಮೇಲೆ ಅತಿ ಸಣ್ಣ ಹಳದಿ ಚುಕ್ಕೆಗಳು',
                                                                       'ಎಲೆಗಳ ಕೆಳಭಾಗದಲ್ಲಿ ಸೂಕ್ಷ್ಮ ಜಾಲ',
                                                                       'ಎಲೆಗಳು ಕಂಚಿನ ಬಣ್ಣಕ್ಕೆ ತಿರುಗುವುದು',
                                                                       'ಎಲೆಗಳು ಒಣಗುವುದು'],
                                                          'solution': ['ಹುಳುಗಳ ದಾಳಿ ತೀವ್ರವಾಗಿದ್ದರೆ ಮಿಟಿಸೈಡ್ '
                                                                       'ಸಿಂಪಡಿಸಿ.',
                                                                       'ಸೂಕ್ತವಾಗಿದ್ದರೆ ಗಿಡಗಳ ಸುತ್ತ ತೇವಾಂಶ '
                                                                       'ಹೆಚ್ಚಿಸಿ.',
                                                                       'ತೀವ್ರವಾಗಿ ಬಾಧಿತ ಎಲೆಗಳನ್ನು '
                                                                       'ತೆಗೆದುಹಾಕಿ.',
                                                                       'ಲೇಡಿಬಗ್\u200cಗಳಂತಹ ನೈಸರ್ಗಿಕ '
                                                                       'ಶತ್ರುಗಳನ್ನು ಉತ್ತೇಜಿಸಿ.']}},
 'Tomato___Target_Spot': {'en': {'cause': 'Target spot is caused by the fungus Corynespora cassiicola.',
                                 'symptoms': ['Circular brown lesions',
                                              'Yellow halos around spots',
                                              'Leaf blight',
                                              'Fruit spotting'],
                                 'solution': ['Remove infected leaves.',
                                              'Apply recommended fungicides.',
                                              'Improve air circulation.',
                                              'Avoid excessive irrigation.']},
                          'kn': {'cause': 'ಟಾರ್ಗೆಟ್ ಕಲೆ ರೋಗವು Corynespora cassiicola ಎಂಬ ಶಿಲೀಂಧ್ರದಿಂದ '
                                          'ಉಂಟಾಗುತ್ತದೆ.',
                                 'symptoms': ['ವೃತ್ತಾಕಾರದ ಕಂದು ಗಾಯಗಳು',
                                              'ಕಲೆಗಳ ಸುತ್ತ ಹಳದಿ ವಲಯಗಳು',
                                              'ಎಲೆ ಅಂಗಮಾರಿ',
                                              'ಹಣ್ಣುಗಳ ಮೇಲೆ ಕಲೆಗಳು'],
                                 'solution': ['ಸೋಂಕಿತ ಎಲೆಗಳನ್ನು ತೆಗೆದುಹಾಕಿ.',
                                              'ಶಿಫಾರಸು ಮಾಡಿದ ಶಿಲೀಂಧ್ರನಾಶಕ ಬಳಸಿ.',
                                              'ಗಾಳಿಯ ಹರಿವು ಸುಧಾರಿಸಿ.',
                                              'ಅತಿಯಾದ ನೀರಾವರಿಯನ್ನು ತಪ್ಪಿಸಿ.']}},
 'Tomato___Tomato_Yellow_Leaf_Curl_Virus': {'en': {'cause': 'Tomato Yellow Leaf Curl Virus is transmitted '
                                                            'primarily by whiteflies.',
                                                   'symptoms': ['Yellow curled leaves',
                                                                'Stunted plant growth',
                                                                'Reduced flowering',
                                                                'Poor fruit production'],
                                                   'solution': ['Control whiteflies using recommended '
                                                                'insecticides.',
                                                                'Remove infected plants immediately.',
                                                                'Use virus-resistant tomato varieties.',
                                                                'Keep the field free of weeds.']},
                                            'kn': {'cause': 'ಟೊಮೇಟೊ ಹಳದಿ ಎಲೆ ಮುರುಟು ವೈರಸ್ ಮುಖ್ಯವಾಗಿ ಬಿಳಿ '
                                                            'ನೊಣಗಳಿಂದ ಹರಡುತ್ತದೆ.',
                                                   'symptoms': ['ಹಳದಿಯಾಗಿ ಮಡಚಿಕೊಂಡ ಎಲೆಗಳು',
                                                                'ಗಿಡದ ಬೆಳವಣಿಗೆ ಕುಂಠಿತವಾಗುವುದು',
                                                                'ಹೂಬಿಡುವಿಕೆ ಕಡಿಮೆಯಾಗುವುದು',
                                                                'ಹಣ್ಣಿನ ಉತ್ಪಾದನೆ ಕಡಿಮೆಯಾಗುವುದು'],
                                                   'solution': ['ಶಿಫಾರಸು ಮಾಡಿದ ಕೀಟನಾಶಕಗಳಿಂದ ಬಿಳಿ ನೊಣಗಳನ್ನು '
                                                                'ನಿಯಂತ್ರಿಸಿ.',
                                                                'ಸೋಂಕಿತ ಗಿಡಗಳನ್ನು ತಕ್ಷಣ ತೆಗೆದುಹಾಕಿ.',
                                                                'ವೈರಸ್ ನಿರೋಧಕ ಟೊಮೇಟೊ ತಳಿಗಳನ್ನು ಬಳಸಿ.',
                                                                'ಹೊಲವನ್ನು ಕಳೆರಹಿತವಾಗಿಡಿ.']}},
 'Tomato___Tomato_mosaic_virus': {'en': {'cause': 'Tomato mosaic virus spreads through infected seeds, tools '
                                                  'and plant contact.',
                                         'symptoms': ['Mosaic light and dark green leaf pattern',
                                                      'Leaf curling',
                                                      'Stunted growth',
                                                      'Poor fruit quality'],
                                         'solution': ['Remove infected plants immediately.',
                                                      'Disinfect gardening tools regularly.',
                                                      'Avoid handling plants after tobacco use.',
                                                      'Use certified virus-free seeds.']},
                                  'kn': {'cause': 'ಟೊಮೇಟೊ ಮೊಸಾಯಿಕ್ ವೈರಸ್ ಸೋಂಕಿತ ಬೀಜಗಳು, ಸಾಧನಗಳು ಮತ್ತು ಗಿಡಗಳ '
                                                  'ಪರಸ್ಪರ ಸ್ಪರ್ಶದಿಂದ ಹರಡುತ್ತದೆ.',
                                         'symptoms': ['ಎಲೆಗಳಲ್ಲಿ ತಿಳಿ ಮತ್ತು ಗಾಢ ಹಸಿರು ಮೊಸಾಯಿಕ್ ವಿನ್ಯಾಸ',
                                                      'ಎಲೆಗಳು ಮಡಚಿಕೊಳ್ಳುವುದು',
                                                      'ಬೆಳವಣಿಗೆ ಕುಂಠಿತವಾಗುವುದು',
                                                      'ಹಣ್ಣಿನ ಗುಣಮಟ್ಟ ಕಡಿಮೆಯಾಗುವುದು'],
                                         'solution': ['ಸೋಂಕಿತ ಗಿಡಗಳನ್ನು ತಕ್ಷಣ ತೆಗೆದುಹಾಕಿ.',
                                                      'ತೋಟಗಾರಿಕಾ ಸಾಧನಗಳನ್ನು ನಿಯಮಿತವಾಗಿ ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಿ.',
                                                      'ತಂಬಾಕು ಬಳಕೆಯ ನಂತರ ಗಿಡಗಳನ್ನು ಮುಟ್ಟುವುದನ್ನು ತಪ್ಪಿಸಿ.',
                                                      'ಪ್ರಮಾಣೀಕೃತ ವೈರಸ್ ರಹಿತ ಬೀಜಗಳನ್ನು ಬಳಸಿ.']}},
 'Tomato___healthy': {'en': {'cause': 'Healthy tomato plant with no visible disease symptoms.',
                             'symptoms': ['Bright green healthy leaves',
                                          'Normal flowering',
                                          'Healthy fruit development',
                                          'Strong stem growth'],
                             'solution': ['Maintain balanced fertilization.',
                                          'Water plants regularly without overwatering.',
                                          'Inspect plants weekly for pests and diseases.',
                                          'Keep the growing area clean.']},
                      'kn': {'cause': 'ಯಾವುದೇ ಗೋಚರ ರೋಗಲಕ್ಷಣಗಳಿಲ್ಲದ ಆರೋಗ್ಯಕರ ಟೊಮೇಟೊ ಗಿಡ.',
                             'symptoms': ['ಪ್ರಕಾಶಮಾನ ಹಸಿರು ಆರೋಗ್ಯಕರ ಎಲೆಗಳು',
                                          'ಸಾಮಾನ್ಯ ಹೂಬಿಡುವಿಕೆ',
                                          'ಹಣ್ಣುಗಳ ಆರೋಗ್ಯಕರ ಬೆಳವಣಿಗೆ',
                                          'ಬಲವಾದ ಕಾಂಡದ ಬೆಳವಣಿಗೆ'],
                             'solution': ['ಸಮತೋಲನ ಗೊಬ್ಬರ ಬಳಸಿ.',
                                          'ಹೆಚ್ಚು ನೀರು ಹಾಕದೆ ಗಿಡಗಳಿಗೆ ನಿಯಮಿತವಾಗಿ ನೀರು ಹಾಕಿ.',
                                          'ಕೀಟಗಳು ಮತ್ತು ರೋಗಗಳಿಗಾಗಿ ಪ್ರತಿ ವಾರ ಗಿಡಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.',
                                          'ಬೆಳೆ ಪ್ರದೇಶವನ್ನು ಸ್ವಚ್ಛವಾಗಿಡಿ.']}}}
